### ISSUE TITLE
Ruby group capstone - Catalog of my things

### ISSUE THREAD

**Issue by paulinagonzalezc** [paulinagonzalezc/ruby-capstone-catalog#28]
## Ruby group capstone - Catalog of my things

Link to repo: https://github.com/paulinagonzalezc/ruby-capstone-catalog

Hello, we are a team of 4 and here is how we distributed the work:
Team member 1: @david63011 
Team member 2: @paulinagonzalezc 
Team member 3: @Zia123456 
Team member 4: @storres20

**Comment by Whoistolu** [comment]
### Hi Team,
@paulinagonzalezc , @Zia123456 , @storres20 and @david63011 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

### Highlight
🔆 Link to their GitHub project provided
🔆Information about the number of people in their group provided
🔆 Each card on the board has a descriptive title
🔆 Each card on the board has a description of the task
🔆 All cards are assigned to a team member each

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
